### ISSUE TITLE
Prevent data loss due to composer update

### ISSUE THREAD

**Issue by mattpilott** [wp-kit/rest-kit#1]
I ran composer update and npm run build this morn and my blocks disappeared, seems as though it cleared any modifications to the restkit theme

**Comment by terence1990** [comment]
@matt3224 this is a big oversight - I think I’ll need to do a couple of things.

> Change composer type to wordpress-themekit as oppose to wordpress-theme to avoid it being picked up by bedrock’s installer paths 

> Add a binary in composer.json to wpkit/utils which developer can run at any time to copy rest-kit to theme folder (for either Wordpress or Bedrock) and if rest-kit already exists rebase current files to the version that was previously deployed and then merge the latest version for new changes.

**Comment by terence1990** [comment]
@matt3224 data-loss is now prevented - be sure to follow the steps on the other issue regarding shortening paths to field data to resolve the data-loss issue once and for all: https://github.com/wp-kit/rest-kit/issues/3#issuecomment-663124071.

I will open the second issue regarding a binary to easily merge updates to rest-kit, for now the README shows how the theme can be copied via `cp` command
