### ISSUE TITLE
Rest response does not respect ACF output option

### ISSUE THREAD

**Issue by mattpilott** [wp-kit/rest-kit#2]
If i have a block with a field like link, and i set the output to `url` it comes through as an array, which is the default.

If i have a block with a field like post object and i set the output to `post object` it comes through as an id which is not the default.

This is confusing and i'm unsure why these out puts differ

**Comment by terence1990** [comment]
@matt3224 are you sure you mean url comes through as array? That’s usually just a string like text. Think you may mean image which can come through as an array with size information etc.

I think I need to add some post-processing similar to what acf-to-rest does which applies ACF filters against stored values. The ids are stored so we need to apply the filters to these. Hopefully it should be a case of just passing through one single filter or function that ACF have provided.

I’ll make this change in the Gutenberg object plugin.

**Comment by terence1990** [comment]
@matt3224 this has now been resolved in latest release of wp-kit/gutenberg-object-plugin.

Please follow the steps to upgrade your project on the other issue you raised regarding shortening path to field data - these steps will help you avoid the overwriting/data-loss issue once and for all too:

https://github.com/wp-kit/rest-kit/issues/3#issuecomment-663124071

**Comment by mattpilott** [comment]
I did mean link btw, just to confirm

**Comment by terence1990** [comment]
@matt3224 ok - the latest changes just default to acf defaults now so it should be as expected after following the steps on the other issue
