### ISSUE TITLE
Prevent thread crash for plugins like Yoast

### ISSUE THREAD

**Issue by mattpilott** [wp-kit/rest-kit#6]
![Screenshot 2020-07-25 at 21 04 53](https://user-images.githubusercontent.com/2401925/88465401-aecb0100-ceba-11ea-9bb5-956ffde528b6.png)

This means you cant change tabs or configure yoast whilst restkit is activated

**Comment by terence1990** [comment]
@matt3224  These are the changes you'll need to make in your project which I have merged into master branch of rest-kit:

https://github.com/wp-kit/rest-kit/pull/7/files

Also, please install dev-master of gutenberg-object plugin:

`composer require wp-kit/gutenberg-object-plugin:"dev-master as 2.0.6"`

And then run `npm run build`
